name: notes_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

#  assets:
#    - assets/fonts/Poppins-Regular.ttf
#
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
